name: cron

on:
  push:
    branches:
      - main
  schedule:
      - cron: "30 17 * * *"
env:
  API_HASH: ${{ secrets.API_HASH }}
  API_ID: ${{ secrets.API_ID }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1                                                                 
      - name: 🐍 Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'                                                   
      - name: 💿 Install scholarly & pyrogram                              
        run: pip install scholarly pyrogram 
      - name: 🍳 run bot.py
        run: |
          cd ${GITHUB_WORKSPACE}/
          python bot.py
      - name: 🚀 Deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -am "feat(auto generate): Updated content"
          git branch --set-upstream-to origin/main
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
